---
title: "Spanish La Liga 2"
author: "Luke Benz"
date: "9/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

The 2nd Spanish Division had some real issues last time I fit this model (I'm pretty sure I fit no fixed intercept in the covariance term, which I've since added).

```{r}
library(tidyverse)
library(rstan)
library(here)
source(here('helpers.R'))
options(mc.cores=parallel::detectCores())

### Read in Data 
df <- 
  read_leage_csvs("Spanish La Liga 2") %>% 
  filter(!is.na(home_score), !is.na(away_score))

### 42 teams across these 5 seasons
team_ids <- team_codes(df)

### Add IDs to data set and prepare it for stan
df <- 
  select(df, home, away, home_score, away_score, season, date) %>% 
  mutate('home_id' = team_ids[home],
         'away_id' = team_ids[away])

head(df)

### List of Stan Params
stan_data <- list(
  num_clubs = length(team_ids),
  num_games = nrow(df),
  home_team_code = df$home_id,
  away_team_code = df$away_id,
  h_goals = df$home_score,
  a_goals = df$away_score
)
```

```{r}
### Fit Model (model 3 w/ fixed intercept in covariance model)
set.seed(73097)
model <- stan(file = here('stan/bvp_goals.stan'), data = stan_data, chains = 3, 
              iter = 7000, warmup = 2000, control = list(adapt_delta = 0.95))

```
### Plots
```{r}
### Attacking Coefficients
plot(model, pars = 'alpha')

### Defensive Coefficients
plot(model, pars = 'delta')

### Covariance Components
plot(model, pars = 'rho')

### Other parameters
pairs(model, pars = c('mu', 'home_field', 'fixed_cov'), las = 1)

```